<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V6ELO8R" failures="1" tests="3" name="Test" time="0.373" errors="0" timestamp="2023-11-26T15:18:56 IST">
  <testcase classname="sqlTests.DataBaseTestCases" name="testFormaTable" time="0.137">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at sqlTests.DataBaseTestCases.testFormaTable(DataBaseTestCases.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testFormaTable -->
  <testcase classname="sqlTests.DataBaseTestCases" name="testItemCountTable" time="0.022"/>
  <testcase classname="sqlTests.DataBaseTestCases" name="testRowTable" time="0.017"/>
</testsuite> <!-- Test -->
